### ISSUE TITLE
Throws an exception under Windows 10 x64 and Python 3.8

### ISSUE THREAD

**Issue by sharpe5** [Vernal-Inertia/simple_scheduler#1]
It appears as if this is the perfect scheduler. I'd love to use it to deploy a task that runs on  a schedule.

However, when running the demo code, it produces this:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\grav\.conda\envs\synth38\lib\multiprocessing\spawn.py", line 107, in spawn_main
    new_handle = reduction.duplicate(pipe_handle,
  File "C:\Users\grav\.conda\envs\synth38\lib\multiprocessing\reduction.py", line 79, in duplicate
    return _winapi.DuplicateHandle(
OSError: [WinError 6] The handle is invalid
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\grav\.conda\envs\synth38\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\grav\.conda\envs\synth38\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: Can't get attribute 'wait' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\grav\.conda\envs\synth38\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\grav\.conda\envs\synth38\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: Can't get attribute 'target' on <module '__main__' (built-in)>
```

**Comment by tanveer-sayyed** [comment]
Oh! Yes I work on Linux only and not windows.
Let me check for solutions. Please give me some time.
Thanks.

**Comment by tanveer-sayyed** [comment]
Btw is this the complete traceback?

**Comment by sharpe5** [comment]
> 
> 
> Btw is this the complete traceback?

Yes.

Should be fairly easy to reproduce. I believe that [Python runs under Wine](https://askubuntu.com/questions/330141/install-python-in-wine). I know that `multiprocessing` works on Linux but not Windows (due to a lack of `fork` on Windows). I suspect that altering the library to use [joblib](https://pypi.org/project/joblib/) might make it compatible with Windows? I know that `joblib` just works on Windows, whereas most of the other parallel processing libs only work on Linux.

Happy to test anything on my machine.

**Comment by tanveer-sayyed** [comment]
I tried searching for alternatives and found the following solution which might work. I need your help to try this, because I do not have windows installed. In case this does not work then I'll have to finally install Windows and work accordingly.
 
Please download the attached folder and run example.py [Issue_1.zip](https://github.com/Vernal-Inertia/simple_scheduler/files/6489954/Issue_1.zip)
Before running please do - pip install multiprocess.

Thanks.

**Comment by sharpe5** [comment]
Thanks! It seems to work nicely, but it has an odd warning message which might need suppressing.

My version of Python:

```
S:\github\test>python
Python 3.7.5 (tags/v3.7.5:5c02a39a0b, Oct 15 2019, 00:11:34) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> ^Z
```

And the output:
```
S:\github\test>python example.py

'functools.partial' object has no attribute '__qualname__'

'functools.partial' object has no attribute '__qualname__'

'functools.partial' object has no attribute '__qualname__'
I waited 10 seconds. [Sun May 16 21:22:02 2021]

'functools.partial' object has no attribute '__qualname__'
I waited 10 seconds. [Sun May 16 21:22:07 2021]

'functools.partial' object has no attribute '__qualname__'
I waited 10 seconds. [Sun May 16 21:22:12 2021]
```

**Comment by tanveer-sayyed** [comment]
Thank you for going the extra mile and helping me out! Really, appreciate it!

So now we know "multiprocess" works in both Linux and Windows. I'll update the code
today and let you know. Secondly, regarding the warning, I think it can be removed
by calling functools.partial.func.__qualname__ instead of functools.partial.__qualname__

Will get back to you in a while.

**Comment by tanveer-sayyed** [comment]
Please install the [latest version](https://pypi.org/project/simple-scheduler/1.0.5/)
and, if resolved, close the issue.

**Comment by sharpe5** [comment]
Perfect! Closing issue.

Output of example.py in [Issue_1.zip](https://github.com/Vernal-Inertia/simple_scheduler/files/6489954/Issue_1.zip):
```
S:\github\test>python example.py

Mon May 17 09:05:19 2021 :: wait [recurring | 5-second(s)]

Mon May 17 09:05:24 2021 :: wait [recurring | 5-second(s)]

Mon May 17 09:05:29 2021 :: wait [recurring | 5-second(s)]
I waited 10 seconds. [Mon May 17 09:05:29 2021]

Mon May 17 09:05:34 2021 :: wait [recurring | 5-second(s)]
I waited 10 seconds. [Mon May 17 09:05:34 2021]

Mon May 17 09:05:39 2021 :: wait [recurring | 5-second(s)]
I waited 10 seconds. [Mon May 17 09:05:39 2021]
```
